// ── SDG 목표 데이터 ──────────────────────────────────────
const SDG_DATA = [
  {
    id: 1, color: '#E5243B', icon: '🏠',
    ko: { title: '빈곤 종식', desc: '모든 곳에서 모든 형태의 빈곤을 종식한다.',
          targets: ['1.1 하루 1.25달러 미만으로 생활하는 극빈층 퇴치', '1.2 빈곤층 비율 절반 감축', '1.3 사회 보호 시스템 구축'] },
    en: { title: 'No Poverty', desc: 'End poverty in all its forms everywhere.',
          targets: ['1.1 Eradicate extreme poverty', '1.2 Reduce poverty by half', '1.3 Implement social protection systems'] },
    ja: { title: '貧困をなくそう', desc: 'あらゆる場所のあらゆる形態の貧困を終わらせる。',
          targets: ['1.1 極度の貧困を撲滅', '1.2 貧困を半減', '1.3 社会保護制度の構築'] },
    id: { title: 'Tanpa Kemiskinan', desc: 'Mengakhiri segala bentuk kemiskinan di mana pun.',
          targets: ['1.1 Menghapus kemiskinan ekstrem', '1.2 Mengurangi kemiskinan setengahnya', '1.3 Membangun sistem perlindungan sosial'] }
  },
  {
    id: 2, color: '#DDA63A', icon: '🌾',
    ko: { title: '기아 종식', desc: '기아를 종식하고 식량 안보를 달성하며 지속가능한 농업을 증진한다.',
          targets: ['2.1 기아 종식 및 식량 안보', '2.2 모든 형태의 영양결핍 해소', '2.3 농업 생산성 향상'] },
    en: { title: 'Zero Hunger', desc: 'End hunger, achieve food security and improved nutrition.',
          targets: ['2.1 End hunger and ensure food security', '2.2 End all forms of malnutrition', '2.3 Double agricultural productivity'] },
    ja: { title: '飢餓をゼロに', desc: '飢餓を終わらせ、食料安全保障及び栄養改善を実現する。',
          targets: ['2.1 飢餓をなくす', '2.2 あらゆる形態の栄養不良解消', '2.3 農業生産性の向上'] },
    id: { title: 'Tanpa Kelaparan', desc: 'Mengakhiri kelaparan, mencapai ketahanan pangan.',
          targets: ['2.1 Mengakhiri kelaparan', '2.2 Menghilangkan kekurangan gizi', '2.3 Meningkatkan produktivitas pertanian'] }
  },
  {
    id: 3, color: '#4C9F38', icon: '💚',
    ko: { title: '건강과 웰빙', desc: '모든 연령층의 건강한 삶을 보장하고 웰빙을 증진한다.',
          targets: ['3.1 모성 사망률 감소', '3.2 신생아·아동 사망 예방', '3.3 전염병 퇴치'] },
    en: { title: 'Good Health and Well-being', desc: 'Ensure healthy lives and promote well-being for all at all ages.',
          targets: ['3.1 Reduce maternal mortality', '3.2 End preventable child deaths', '3.3 End epidemics'] },
    ja: { title: 'すべての人に健康と福祉を', desc: 'あらゆる年齢のすべての人々の健康的な生活を確保する。',
          targets: ['3.1 妊産婦死亡率の削減', '3.2 子どもの死亡予防', '3.3 感染症の撲滅'] },
    id: { title: 'Kehidupan Sehat dan Sejahtera', desc: 'Menjamin kehidupan yang sehat dan meningkatkan kesejahteraan.',
          targets: ['3.1 Mengurangi angka kematian ibu', '3.2 Mengakhiri kematian bayi', '3.3 Mengakhiri epidemi'] }
  },
  {
    id: 4, color: '#C5192D', icon: '📚',
    ko: { title: '양질의 교육', desc: '포용적이고 공평한 양질의 교육을 보장하고 평생학습 기회를 증진한다.',
          targets: ['4.1 무상 초·중등교육 보장', '4.2 영유아 교육 접근성', '4.3 직업·고등교육 접근성'] },
    en: { title: 'Quality Education', desc: 'Ensure inclusive and equitable quality education.',
          targets: ['4.1 Free primary and secondary education', '4.2 Early childhood development', '4.3 Access to vocational training'] },
    ja: { title: '質の高い教育をみんなに', desc: 'すべての人々に包摂的かつ公正な質の高い教育を確保する。',
          targets: ['4.1 初等・中等教育の無償化', '4.2 幼児教育へのアクセス', '4.3 職業訓練へのアクセス'] },
    id: { title: 'Pendidikan Berkualitas', desc: 'Menjamin pendidikan yang inklusif dan berkualitas.',
          targets: ['4.1 Pendidikan dasar dan menengah gratis', '4.2 Pengembangan anak usia dini', '4.3 Akses pelatihan kejuruan'] }
  },
  {
    id: 5, color: '#FF3A21', icon: '⚖️',
    ko: { title: '성평등', desc: '성평등을 달성하고 모든 여성과 소녀의 역량을 강화한다.',
          targets: ['5.1 모든 차별 철폐', '5.2 여성·소녀 폭력 근절', '5.3 조혼·강제결혼 철폐'] },
    en: { title: 'Gender Equality', desc: 'Achieve gender equality and empower all women and girls.',
          targets: ['5.1 End discrimination against women', '5.2 Eliminate violence against women', '5.3 Eliminate child marriage'] },
    ja: { title: 'ジェンダー平等を実現しよう', desc: 'ジェンダー平等を達成し、すべての女性及び女児の能力強化を行う。',
          targets: ['5.1 差別の撤廃', '5.2 暴力の根絶', '5.3 児童婚の廃止'] },
    id: { title: 'Kesetaraan Gender', desc: 'Mencapai kesetaraan gender dan memberdayakan perempuan.',
          targets: ['5.1 Menghapus diskriminasi', '5.2 Mengakhiri kekerasan', '5.3 Menghapus pernikahan anak'] }
  },
  {
    id: 6, color: '#26BDE2', icon: '💧',
    ko: { title: '깨끗한 물과 위생', desc: '모든 사람이 물과 위생 시설을 이용할 수 있도록 한다.',
          targets: ['6.1 안전한 식수 보편적 접근', '6.2 위생 시설 보편적 접근', '6.3 수질 개선'] },
    en: { title: 'Clean Water and Sanitation', desc: 'Ensure availability and sustainable management of water.',
          targets: ['6.1 Universal access to safe water', '6.2 Universal access to sanitation', '6.3 Improve water quality'] },
    ja: { title: '安全な水とトイレを世界中に', desc: 'すべての人々の水と衛生の利用可能性を確保する。',
          targets: ['6.1 安全な水への普遍的アクセス', '6.2 衛生施設へのアクセス', '6.3 水質の改善'] },
    id: { title: 'Air Bersih dan Sanitasi Layak', desc: 'Menjamin ketersediaan air bersih dan sanitasi.',
          targets: ['6.1 Akses universal air aman', '6.2 Akses sanitasi', '6.3 Meningkatkan kualitas air'] }
  },
  {
    id: 7, color: '#FCC30B', icon: '⚡',
    ko: { title: '저렴하고 깨끗한 에너지', desc: '모든 사람이 저렴하고 신뢰할 수 있는 청정 에너지를 이용할 수 있도록 한다.',
          targets: ['7.1 현대적 에너지 서비스 보편화', '7.2 재생에너지 비중 확대', '7.3 에너지 효율 개선'] },
    en: { title: 'Affordable and Clean Energy', desc: 'Ensure access to affordable, reliable, and clean energy.',
          targets: ['7.1 Universal access to modern energy', '7.2 Increase renewable energy', '7.3 Improve energy efficiency'] },
    ja: { title: 'エネルギーをみんなにそしてクリーンに', desc: '手頃で信頼でき、持続可能なエネルギーへのアクセスを確保する。',
          targets: ['7.1 現代的エネルギーへの普遍的アクセス', '7.2 再生可能エネルギーの拡大', '7.3 エネルギー効率の改善'] },
    id: { title: 'Energi Bersih dan Terjangkau', desc: 'Menjamin akses energi yang terjangkau dan berkelanjutan.',
          targets: ['7.1 Akses universal energi modern', '7.2 Meningkatkan energi terbarukan', '7.3 Meningkatkan efisiensi energi'] }
  },
  {
    id: 8, color: '#A21942', icon: '💼',
    ko: { title: '양질의 일자리와 경제성장', desc: '지속적이고 포용적인 경제성장과 양질의 일자리를 증진한다.',
          targets: ['8.1 1인당 경제성장 유지', '8.2 생산성 향상', '8.5 완전고용 달성'] },
    en: { title: 'Decent Work and Economic Growth', desc: 'Promote sustained, inclusive economic growth and decent work.',
          targets: ['8.1 Sustain per capita economic growth', '8.2 Achieve higher productivity', '8.5 Achieve full employment'] },
    ja: { title: '働きがいも経済成長も', desc: '包摂的かつ持続可能な経済成長及び雇用を促進する。',
          targets: ['8.1 一人あたりの経済成長', '8.2 生産性の向上', '8.5 完全雇用の達成'] },
    id: { title: 'Pekerjaan Layak dan Pertumbuhan Ekonomi', desc: 'Mendorong pertumbuhan ekonomi yang inklusif.',
          targets: ['8.1 Pertumbuhan ekonomi per kapita', '8.2 Meningkatkan produktivitas', '8.5 Mencapai lapangan kerja penuh'] }
  },
  {
    id: 9, color: '#FD6925', icon: '🏭',
    ko: { title: '산업·혁신·인프라', desc: '회복력 있는 인프라를 구축하고 포용적·지속가능한 산업화를 증진한다.',
          targets: ['9.1 지속가능한 인프라 개발', '9.2 포용적 산업화', '9.5 과학 연구·혁신 강화'] },
    en: { title: 'Industry, Innovation and Infrastructure', desc: 'Build resilient infrastructure and foster innovation.',
          targets: ['9.1 Develop sustainable infrastructure', '9.2 Promote inclusive industrialization', '9.5 Enhance scientific research'] },
    ja: { title: '産業と技術革新の基盤をつくろう', desc: '強靭なインフラを整備し、包摂的な産業化を促進する。',
          targets: ['9.1 持続可能なインフラ', '9.2 包摂的な産業化', '9.5 科学研究の強化'] },
    id: { title: 'Industri, Inovasi dan Infrastruktur', desc: 'Membangun infrastruktur yang tangguh dan mendorong inovasi.',
          targets: ['9.1 Mengembangkan infrastruktur berkelanjutan', '9.2 Industrialisasi inklusif', '9.5 Memperkuat riset ilmiah'] }
  },
  {
    id: 10, color: '#DD1367', icon: '🟰',
    ko: { title: '불평등 감소', desc: '국가 내 및 국가 간 불평등을 감소시킨다.',
          targets: ['10.1 하위 40% 소득 성장', '10.2 사회적 포용 증진', '10.3 기회 균등 보장'] },
    en: { title: 'Reduced Inequalities', desc: 'Reduce inequality within and among countries.',
          targets: ['10.1 Income growth for the bottom 40%', '10.2 Promote social inclusion', '10.3 Ensure equal opportunity'] },
    ja: { title: '人や国の不平等をなくそう', desc: '国内及び国家間の不平等を是正する。',
          targets: ['10.1 下位40%の所得成長', '10.2 社会的包摂の促進', '10.3 機会均等の確保'] },
    id: { title: 'Berkurangnya Kesenjangan', desc: 'Mengurangi ketimpangan di dalam dan antar negara.',
          targets: ['10.1 Pertumbuhan pendapatan 40% terbawah', '10.2 Mendorong inklusi sosial', '10.3 Memastikan kesempatan setara'] }
  },
  {
    id: 11, color: '#FD9D24', icon: '🏙️',
    ko: { title: '지속가능한 도시와 공동체', desc: '도시와 주거지를 포용적이고 안전하며 지속가능하게 만든다.',
          targets: ['11.1 안전한 주거 접근', '11.2 지속가능한 교통', '11.4 문화·자연유산 보호'] },
    en: { title: 'Sustainable Cities and Communities', desc: 'Make cities inclusive, safe, and sustainable.',
          targets: ['11.1 Access to safe housing', '11.2 Sustainable transportation', '11.4 Protect cultural heritage'] },
    ja: { title: '住み続けられるまちづくりを', desc: '都市を包摂的で安全かつ強靭で持続可能にする。',
          targets: ['11.1 安全な住居へのアクセス', '11.2 持続可能な交通', '11.4 文化遺産の保護'] },
    id: { title: 'Kota dan Permukiman yang Berkelanjutan', desc: 'Menjadikan kota inklusif, aman dan berkelanjutan.',
          targets: ['11.1 Akses perumahan yang aman', '11.2 Transportasi berkelanjutan', '11.4 Melindungi warisan budaya'] }
  },
  {
    id: 12, color: '#BF8B2E', icon: '♻️',
    ko: { title: '책임감 있는 소비와 생산', desc: '지속가능한 소비와 생산 양식을 보장한다.',
          targets: ['12.2 천연자원 지속가능한 관리', '12.3 식품 낭비 절반 감축', '12.5 폐기물 감소'] },
    en: { title: 'Responsible Consumption and Production', desc: 'Ensure sustainable consumption and production patterns.',
          targets: ['12.2 Sustainable management of natural resources', '12.3 Halve global food waste', '12.5 Reduce waste generation'] },
    ja: { title: 'つくる責任つかう責任', desc: '持続可能な消費生産形態を確保する。',
          targets: ['12.2 天然資源の持続可能な管理', '12.3 食品廃棄物の半減', '12.5 廃棄物の削減'] },
    id: { title: 'Konsumsi dan Produksi yang Bertanggung Jawab', desc: 'Memastikan pola konsumsi dan produksi yang berkelanjutan.',
          targets: ['12.2 Pengelolaan sumber daya alam berkelanjutan', '12.3 Mengurangi limbah makanan', '12.5 Mengurangi timbulan sampah'] }
  },
  {
    id: 13, color: '#3F7E44', icon: '🌍',
    ko: { title: '기후 행동', desc: '기후변화와 그 영향에 대응하는 긴급 행동을 취한다.',
          targets: ['13.1 기후 재해 대응력 강화', '13.2 기후변화 정책 통합', '13.3 기후변화 교육 강화'] },
    en: { title: 'Climate Action', desc: 'Take urgent action to combat climate change.',
          targets: ['13.1 Strengthen resilience to climate hazards', '13.2 Integrate climate change measures', '13.3 Improve climate change education'] },
    ja: { title: '気候変動に具体的な対策を', desc: '気候変動及びその影響を軽減するための緊急対策を講じる。',
          targets: ['13.1 気候関連災害への対応力強化', '13.2 気候変動対策の統合', '13.3 気候変動教育の強化'] },
    id: { title: 'Penanganan Perubahan Iklim', desc: 'Mengambil tindakan segera untuk mengatasi perubahan iklim.',
          targets: ['13.1 Memperkuat ketahanan terhadap bencana iklim', '13.2 Mengintegrasikan kebijakan iklim', '13.3 Meningkatkan pendidikan iklim'] }
  },
  {
    id: 14, color: '#0A97D9', icon: '🐠',
    ko: { title: '수중 생태계', desc: '지속가능한 발전을 위해 해양·연안 생태계를 보전한다.',
          targets: ['14.1 해양 오염 방지', '14.2 해양 생태계 보호', '14.3 해양 산성화 최소화'] },
    en: { title: 'Life Below Water', desc: 'Conserve and sustainably use the oceans and marine resources.',
          targets: ['14.1 Prevent marine pollution', '14.2 Protect marine ecosystems', '14.3 Minimize ocean acidification'] },
    ja: { title: '海の豊かさを守ろう', desc: '海洋及び海洋資源を持続可能な開発に向けて保全する。',
          targets: ['14.1 海洋汚染の防止', '14.2 海洋生態系の保護', '14.3 海洋酸性化の最小化'] },
    id: { title: 'Ekosistem Lautan', desc: 'Melestarikan dan memanfaatkan samudra dan sumber daya laut secara berkelanjutan.',
          targets: ['14.1 Mencegah polusi laut', '14.2 Melindungi ekosistem laut', '14.3 Meminimalkan pengasaman laut'] }
  },
  {
    id: 15, color: '#56C02B', icon: '🌳',
    ko: { title: '육상 생태계', desc: '육상 생태계를 보호하고 지속가능하게 관리하며 생물 다양성 손실을 막는다.',
          targets: ['15.1 육상·담수 생태계 보전', '15.2 삼림 지속가능 관리', '15.5 생물다양성 손실 방지'] },
    en: { title: 'Life on Land', desc: 'Protect, restore and promote sustainable use of terrestrial ecosystems.',
          targets: ['15.1 Conserve terrestrial ecosystems', '15.2 Sustainable forest management', '15.5 Halt biodiversity loss'] },
    ja: { title: '陸の豊かさも守ろう', desc: '陸域生態系の保護及び生物多様性損失の阻止を図る。',
          targets: ['15.1 陸域生態系の保全', '15.2 持続可能な森林管理', '15.5 生物多様性損失の阻止'] },
    id: { title: 'Ekosistem Daratan', desc: 'Melindungi, merestorasi dan meningkatkan penggunaan ekosistem daratan.',
          targets: ['15.1 Melestarikan ekosistem darat', '15.2 Pengelolaan hutan berkelanjutan', '15.5 Menghentikan hilangnya keanekaragaman hayati'] }
  },
  {
    id: 16, color: '#00689D', icon: '🏛️',
    ko: { title: '평화·정의·강력한 제도', desc: '지속가능한 발전을 위해 평화롭고 포용적인 사회를 증진한다.',
          targets: ['16.1 모든 형태의 폭력 감소', '16.2 아동 학대·착취 근절', '16.3 법치주의 증진'] },
    en: { title: 'Peace, Justice and Strong Institutions', desc: 'Promote peaceful and inclusive societies for sustainable development.',
          targets: ['16.1 Reduce violence everywhere', '16.2 End abuse and exploitation of children', '16.3 Promote the rule of law'] },
    ja: { title: '平和と公正をすべての人に', desc: '持続可能な開発のための平和で包摂的な社会を促進する。',
          targets: ['16.1 あらゆる暴力の大幅な減少', '16.2 子どもへの虐待の根絶', '16.3 法の支配の促進'] },
    id: { title: 'Perdamaian, Keadilan dan Kelembagaan yang Tangguh', desc: 'Mendorong masyarakat yang damai dan inklusif.',
          targets: ['16.1 Mengurangi kekerasan', '16.2 Mengakhiri kekerasan terhadap anak', '16.3 Mendorong supremasi hukum'] }
  },
  {
    id: 17, color: '#19486A', icon: '🤝',
    ko: { title: '목표 달성을 위한 파트너십', desc: '이행 수단을 강화하고 지속가능한 발전을 위한 글로벌 파트너십을 활성화한다.',
          targets: ['17.1 개발도상국 재정 역량 강화', '17.6 과학기술·혁신 협력 강화', '17.17 민관 파트너십 장려'] },
    en: { title: 'Partnerships for the Goals', desc: 'Strengthen the means of implementation and revitalize global partnership.',
          targets: ['17.1 Strengthen domestic resource mobilization', '17.6 Enhance technology cooperation', '17.17 Encourage effective partnerships'] },
    ja: { title: 'パートナーシップで目標を達成しよう', desc: '持続可能な開発のためのグローバル・パートナーシップを強化する。',
          targets: ['17.1 国内資源調達の強化', '17.6 科学技術・イノベーション協力', '17.17 官民パートナーシップの奨励'] },
    id: { title: 'Kemitraan untuk Mencapai Tujuan', desc: 'Memperkuat sarana pelaksanaan dan merevitalisasi kemitraan global.',
          targets: ['17.1 Memperkuat mobilisasi sumber daya', '17.6 Meningkatkan kerja sama teknologi', '17.17 Mendorong kemitraan yang efektif'] }
  }
];

// ── 번역 객체 ────────────────────────────────────────────
const T = {
  ko: {
    header_title: 'SDGs 마켓',
    nav_home: '홈',
    slide2_title: 'SDGs란 무엇인가?',
    slide2_desc: '클릭하여 자세히 알아보기',
    slide3_title: 'SDGs 사전 보기',
    slide3_desc: '17개 목표 상세 보기',
    btn_select: '🛒 선택하기',
    btn_selected: '✅ 선택됨',
    btn_quick: '⚡ 바로 구매',
    toast_added: '장바구니에 담았습니다!',
    toast_removed: '장바구니에서 제거했습니다.',
    cart_bar_text: '개 목표 선택됨',
    btn_view_cart: '장바구니 보기',
    cart_title: '장바구니',
    cart_empty: '장바구니가 비어 있습니다.',
    cart_count: '총',
    cart_count_unit: '개 목표 선택',
    btn_checkout: '구매하기',
    btn_back_home: '홈으로',
    checkout_title: '실천 계획 작성',
    section_orderer: '주문자 정보',
    label_name: '이름 *',
    label_school: '학교명 *',
    label_grade: '학년 *',
    label_class: '반',
    section_items: '선택한 SDGs',
    section_method: '실천 방법',
    method_think: '생각하기',
    method_empathize: '공감하기',
    method_act: '행동하기',
    section_plan: '나의 실천 계획',
    plan_text: '글로 작성',
    plan_draw: '그림으로 그리기',
    plan_both: '글 + 그림',
    plan_placeholder: 'SDGs를 위해 내가 할 수 있는 일을 적어보세요.',
    btn_clear: '지우기',
    btn_submit: '주문하기',
    err_name: '이름을 입력해주세요.',
    err_school: '학교명을 입력해주세요.',
    err_grade: '학년을 선택해주세요.',
    err_plan: '실천 계획을 작성하거나 그림을 그려주세요.',
    receipt_title: '나의 실천 계획서',
    receipt_student: '주문자',
    receipt_goals: '선택한 SDGs',
    receipt_methods: '실천 방법',
    receipt_plan: '나의 실천 계획',
    btn_download: '📥 다운로드',
    btn_print: '🖨️ 인쇄',
    btn_complete: '✅ 완료',
    complete_title: '🎉 실천 계획 완료!',
    complete_msg: 'SDGs를 위한 첫 걸음을 내딛었습니다.',
    btn_go_home: '홈으로 돌아가기',
    sdg_info_title: 'SDGs란?',
    tl_2000: 'MDGs(새천년개발목표) 채택',
    tl_2012: 'Rio+20 지속가능발전 회의',
    tl_2015: 'SDGs 채택 (193개국)',
    tl_2030: '달성 목표 연도',
    pillar_eco: '경제 성장',
    pillar_soc: '사회 발전',
    pillar_env: '환경 보호',
    sdg_dict_title: 'SDGs 사전',
  },
  en: {
    header_title: 'SDGs Market',
    nav_home: 'Home',
    slide2_title: 'What are SDGs?',
    slide2_desc: 'Click to learn more',
    slide3_title: 'SDGs Dictionary',
    slide3_desc: 'View all 17 goals in detail',
    btn_select: '🛒 Select',
    btn_selected: '✅ Selected',
    btn_quick: '⚡ Quick Buy',
    toast_added: 'Added to cart!',
    toast_removed: 'Removed from cart.',
    cart_bar_text: ' goal(s) selected',
    btn_view_cart: 'View Cart',
    cart_title: 'Cart',
    cart_empty: 'Your cart is empty.',
    cart_count: 'Total',
    cart_count_unit: ' goal(s) selected',
    btn_checkout: 'Checkout',
    btn_back_home: 'Back to Home',
    checkout_title: 'Write Your Action Plan',
    section_orderer: 'Student Information',
    label_name: 'Name *',
    label_school: 'School *',
    label_grade: 'Grade *',
    label_class: 'Class',
    section_items: 'Selected SDGs',
    section_method: 'Action Method',
    method_think: 'Think',
    method_empathize: 'Empathize',
    method_act: 'Act',
    section_plan: 'My Action Plan',
    plan_text: 'Write Text',
    plan_draw: 'Draw',
    plan_both: 'Text + Drawing',
    plan_placeholder: 'Write what you can do for SDGs.',
    btn_clear: 'Clear',
    btn_submit: 'Submit',
    err_name: 'Please enter your name.',
    err_school: 'Please enter your school.',
    err_grade: 'Please select your grade.',
    err_plan: 'Please write or draw your action plan.',
    receipt_title: 'My Action Plan',
    receipt_student: 'Student',
    receipt_goals: 'Selected SDGs',
    receipt_methods: 'Action Methods',
    receipt_plan: 'My Action Plan',
    btn_download: '📥 Download',
    btn_print: '🖨️ Print',
    btn_complete: '✅ Complete',
    complete_title: '🎉 Action Plan Complete!',
    complete_msg: 'You have taken the first step for SDGs.',
    btn_go_home: 'Back to Home',
    sdg_info_title: 'What are SDGs?',
    tl_2000: 'MDGs Adopted',
    tl_2012: 'Rio+20 Conference',
    tl_2015: 'SDGs Adopted (193 countries)',
    tl_2030: 'Target Year',
    pillar_eco: 'Economic Growth',
    pillar_soc: 'Social Development',
    pillar_env: 'Environmental Protection',
    sdg_dict_title: 'SDGs Dictionary',
  },
  ja: {
    header_title: 'SDGsマーケット',
    nav_home: 'ホーム',
    slide2_title: 'SDGsとは？',
    slide2_desc: 'クリックして詳細を見る',
    slide3_title: 'SDGs辞典',
    slide3_desc: '17の目標を見る',
    btn_select: '🛒 選ぶ',
    btn_selected: '✅ 選択済み',
    btn_quick: '⚡ すぐ購入',
    toast_added: 'カートに入れました！',
    toast_removed: 'カートから削除しました。',
    cart_bar_text: '個の目標を選択中',
    btn_view_cart: 'カートを見る',
    cart_title: 'カート',
    cart_empty: 'カートは空です。',
    cart_count: '合計',
    cart_count_unit: '個の目標',
    btn_checkout: '購入する',
    btn_back_home: 'ホームへ',
    checkout_title: '実践計画を書く',
    section_orderer: '注文者情報',
    label_name: '名前 *',
    label_school: '学校名 *',
    label_grade: '学年 *',
    label_class: 'クラス',
    section_items: '選んだSDGs',
    section_method: '実践方法',
    method_think: '考える',
    method_empathize: '共感する',
    method_act: '行動する',
    section_plan: '私の実践計画',
    plan_text: '文章で書く',
    plan_draw: '絵を描く',
    plan_both: '文章 + 絵',
    plan_placeholder: 'SDGsのためにできることを書いてください。',
    btn_clear: 'クリア',
    btn_submit: '注文する',
    err_name: '名前を入力してください。',
    err_school: '学校名を入力してください。',
    err_grade: '学年を選択してください。',
    err_plan: '実践計画を書くか絵を描いてください。',
    receipt_title: '私の実践計画書',
    receipt_student: '注文者',
    receipt_goals: '選んだSDGs',
    receipt_methods: '実践方法',
    receipt_plan: '私の実践計画',
    btn_download: '📥 ダウンロード',
    btn_print: '🖨️ 印刷',
    btn_complete: '✅ 完了',
    complete_title: '🎉 実践計画完了！',
    complete_msg: 'SDGsへの第一歩を踏み出しました。',
    btn_go_home: 'ホームへ戻る',
    sdg_info_title: 'SDGsとは？',
    tl_2000: 'MDGs採択',
    tl_2012: 'リオ+20会議',
    tl_2015: 'SDGs採択（193か国）',
    tl_2030: '達成目標年',
    pillar_eco: '経済成長',
    pillar_soc: '社会開発',
    pillar_env: '環境保護',
    sdg_dict_title: 'SDGs辞典',
  },
  id: {
    header_title: 'Pasar SDGs',
    nav_home: 'Beranda',
    slide2_title: 'Apa itu SDGs?',
    slide2_desc: 'Klik untuk mengetahui lebih lanjut',
    slide3_title: 'Kamus SDGs',
    slide3_desc: 'Lihat 17 tujuan secara detail',
    btn_select: '🛒 Pilih',
    btn_selected: '✅ Dipilih',
    btn_quick: '⚡ Beli Sekarang',
    toast_added: 'Ditambahkan ke keranjang!',
    toast_removed: 'Dihapus dari keranjang.',
    cart_bar_text: ' tujuan dipilih',
    btn_view_cart: 'Lihat Keranjang',
    cart_title: 'Keranjang',
    cart_empty: 'Keranjang kosong.',
    cart_count: 'Total',
    cart_count_unit: ' tujuan dipilih',
    btn_checkout: 'Checkout',
    btn_back_home: 'Kembali ke Beranda',
    checkout_title: 'Tulis Rencana Aksi',
    section_orderer: 'Informasi Siswa',
    label_name: 'Nama *',
    label_school: 'Sekolah *',
    label_grade: 'Kelas *',
    label_class: 'Ruang',
    section_items: 'SDGs yang Dipilih',
    section_method: 'Metode Aksi',
    method_think: 'Berpikir',
    method_empathize: 'Berempati',
    method_act: 'Bertindak',
    section_plan: 'Rencana Aksiku',
    plan_text: 'Tulis Teks',
    plan_draw: 'Gambar',
    plan_both: 'Teks + Gambar',
    plan_placeholder: 'Tulis apa yang bisa kamu lakukan untuk SDGs.',
    btn_clear: 'Hapus',
    btn_submit: 'Kirim',
    err_name: 'Masukkan nama Anda.',
    err_school: 'Masukkan nama sekolah Anda.',
    err_grade: 'Pilih kelas Anda.',
    err_plan: 'Tulis atau gambar rencana aksi Anda.',
    receipt_title: 'Rencana Aksiku',
    receipt_student: 'Siswa',
    receipt_goals: 'SDGs yang Dipilih',
    receipt_methods: 'Metode Aksi',
    receipt_plan: 'Rencana Aksiku',
    btn_download: '📥 Unduh',
    btn_print: '🖨️ Cetak',
    btn_complete: '✅ Selesai',
    complete_title: '🎉 Rencana Aksi Selesai!',
    complete_msg: 'Anda telah mengambil langkah pertama untuk SDGs.',
    btn_go_home: 'Kembali ke Beranda',
    sdg_info_title: 'Apa itu SDGs?',
    tl_2000: 'MDGs Diadopsi',
    tl_2012: 'Konferensi Rio+20',
    tl_2015: 'SDGs Diadopsi (193 negara)',
    tl_2030: 'Tahun Target',
    pillar_eco: 'Pertumbuhan Ekonomi',
    pillar_soc: 'Pembangunan Sosial',
    pillar_env: 'Perlindungan Lingkungan',
    sdg_dict_title: 'Kamus SDGs',
  }
};
